version: '3'
services:
    node-app:
        container_name: node-app
        build:
            context: ./node-app
            dockerfile: Dockerfile
        ports:
            - '8080:8080'
        env_file: .env
        environment:
            - NODE_APP_PORT=$NODE_APP_PORT
        volumes:
            - '${PWD}/node-app:/app'
            - '/app/node_modules'
        networks:
            - app-network
    react-app:
        container_name: react-app
        build:
            context: ./react-app
            dockerfile: Dockerfile
        volumes:
            - '${PWD}/react-app:/app'
            - '/app/node_modules'
        ports:
            - '3000:3000'
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
